services:
  - type: web
    name: openhands-api
    runtime: python
    buildCommand: |
      curl -sSL https://install.python-poetry.org | python3 -
      export PATH="$HOME/.local/bin:$PATH"
      poetry install
    startCommand: >
      export PATH="$HOME/.local/bin:$PATH" &&
      poetry run uvicorn openhands.server.listen:app --host 0.0.0.0 --port 10000
    envVars:
      - key: RUNTIME
        value: "local"
      - key: LOG_ALL_EVENTS
        value: "true"
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
